---
name: run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre_commit_checks:
      runs-on: ubuntu-24.04
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: "3.10"
        - uses: pre-commit/action@v3.0.1
        # run pre-commit ci lite for automated fixes
        - uses: pre-commit-ci/lite-action@v1.1.0
          if: ${{ !cancelled() }}
  tests:
    strategy:
      matrix:
        # matrixed execution for parallel gh-action performance increases
        python_version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-24.04, macos-14]
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Setup poetry
        run: |
          pip install poetry
      - name: Install poetry env
        run: |
          poetry install
      - name: Run pytest
        env:
          # set placeholder API key, required by tests
          PROVIDER_API_KEY: ABCD1234
        run: poetry run pytest
